name: Delete old docker images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old docker images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.repository }}
          package-type: container
          min-versions-to-keep: 2
